export * from './getDiscount'
export * from './getTotalPrice'
export * from './categoryUkr'
export * from './paymentData'
export * from './guaranteeData'
export * from './returnData'
export * from './variables'